os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
services:
  - mysql
  - postgresql
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export export CXX=g++-4.9; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mariadb && mysql.server start; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sleep 5; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi'
  - sleep 15
  - npm install winston@3.2.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
